name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore SimpleFeedReader/SimpleFeedReader.csproj
    - name: Build
      run: dotnet build SimpleFeedReader/SimpleFeedReader.csproj --no-restore
    - name: Test
      run: dotnet test SimpleFeedReader/SimpleFeedReader.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet publish SimpleFeedReader/SimpleFeedReader.csproj -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: website/**
        if-no-files-found: error


